
evaluation:
  experiment_dir:  results/fim_ode_sinData_onlyInitCond-experiment-seed-0_07-27-1430/ # train config, model checkpoint, output_path will be taken from here
  model_checkpoint: best-model # best-model or epoch-<int>
  # output_path: results/fim_ode_sinData_onlyInitCond-experiment-seed-0_07-26-1711/inference/
  evaluation_type: ts
  device_map: cuda
  sample_indices: !!python/tuple [73, 37, 39, 48, 543, 672, 690, 757, 957]
  dataset_param: # all other parameters will be taken from the train config
    split: validation
#   name: base_dataloader
#   path:  data/only_sinusoidal_lowFreq/
#   ds_name: ""
#   dataset_type_name: "dummy"
#   batch_size: 1024
#   test_batch_size: 1024
#   output_fields: !!python/tuple ["fine_grid_grid", "coarse_grid_grid", "coarse_grid_sample_paths", "coarse_grid_observation_mask", "fine_grid_concept_values", "fine_grid_sample_paths"]
#   loader_kwargs:
#     num_workers: 1
