experiment:
  name: AR_LSTM_VANILA_TEST
  name_add_date: True
  seed: [1]
  device_map: cpu # auto, cuda, cpu

distributed:
  enabled: false

model:
  name: AR
  load_in_8bit: false
  load_in_4bit: false
  use_bf16: true
  recurrent_module:
    name: torch.nn.LSTM
    num_layers: 1
    hidden_size: &hidden_size 128
    dropout: 0.1
    bidirectional: false
    batch_first: true
    input_size: 3

  output_head:
    name: fim.models.blocks.Mlp
    in_features: *hidden_size
    out_features: 2
    hidden_layers: !!python/tuple [256, 256]
    hidden_act:
      name: torch.nn.ReLU
    output_act:
      name: torch.nn.ReLU

  peft:
    method: null # null, lora
    r: 32
    lora_alpha: 32
    # target_modules: !!python/tuple ["c_attn", "c_proj", "c_fc"]
    bias: none
    task_type: CAUSAL_LM
    lora_dropout: 0.05
    inference_mode: false

dataset:
  name: base_dataloader
  dataset_type_name: "base"
  path: monash_tsf
  ds_name: nn5_daily # if null it uses the default cache path set for huggingface
  batch_size: 1024
  test_batch_size: 1024
  output_fields: !!python/tuple ["target"]

  loader_kwargs:
    num_workers: 2

  # dataset_kwargs:
  #   download_mode: force_redownload

optimizers: !!python/tuple
  - optimizer_d: # name of the optimizer
      name: torch.optim.AdamW
      lr: 0.0001
      weight_decay: 0.0
      gradient_norm_clipping: null
      # schedulers: !!python/tuple
      #   - name: torch.optim.lr_scheduler.StepLR
      #     step_size: 1
      #     gamma: 0.8
      #     step_type: epoch

trainer:
  name: Trainer
  debug_iterations: null
  precision: bf16 # null fp16 bf16 bf16_mixed fp16_mixed fp32_policy
  epochs: 400
  detect_anomaly: false
  save_every: 1
  gradient_accumulation_steps: 1
  best_metric: rmse
  logging_format: "RANK_%(rank)s - %(asctime)s - %(name)s - %(levelname)s - %(message)s"
  experiment_dir: ./results/
  schedulers: !!python/tuple
    - name: fim.utils.param_scheduler.PeriodicScheduler # ExponentialIncrease, ConstantScheduler, PeriodicScheduler
      label: beta_scheduler
    - name: fim.utils.param_scheduler.ExponentialSchedulerGumbel
      label: temperature_scheduler
      init_temperature: 1
      min_temperature: 0.5
      training_fraction_to_reach_min: 0.7
