experiment:
  name: fim_ode_example
  seed: [1]
  device_map: cuda # auto, cuda, cpu

distributed:
  enabled: false

model:
  name: FIMODE
  load_in_8bit: false
  load_in_4bit: false
  use_bf16: false

  time_encoding:
    name: fim.models.blocks.TimeEncoding
    dim_time: &dim_time 

  trunk_net:
    name: fim.models.blocks.Mlp
    in_features: *dim_time
    out_features: &dim_latent 256
    hidden_layers: !!python/tuple [&hidden_dim_mlp 1024, *hidden_dim_mlp, *hidden_dim_mlp, *hidden_dim_mlp]
    hidden_act:
      name: torch.nn.SELU
    output_act:
      name: torch.nn.SELU
    dropout: &dropout 0.1
  
  branch_net:
    name: fim.models.blocks.Transformer
    num_encoder_blocks: 4
    d_model: *dim_latent
    num_heads: 8
    dropout: *dropout
    residual_mlp:
      name: fim.models.blocks.Mlp
      in_features: *dim_latent
      out_features: *dim_latent
      hidden_layers: !!python/tuple [512]
      hidden_act:
        name: torch.nn.SELU 
      output_act:
        name: torch.nn.SELU
  
  combiner_net:
    name: fim.models.blocks.Mlp
    in_features: *dim_latent
    out_features: *dim_latent
    hidden_layers: !!python/tuple [*hidden_dim_mlp, *hidden_dim_mlp, *hidden_dim_mlp, *hidden_dim_mlp]
    hidden_act:
      name: torch.nn.SELU
    output_act:
      name: torch.nn.SELU
    dropout: *dropout

  vector_field_mean_net:
    name: fim.models.blocks.Mlp
    in_features: *dim_latent
    out_features: 1
    hidden_layers: !!python/tuple []
    output_act:
      name: torch.nn.Identity
    dropout: *dropout

  vector_field_var_net:
    name: fim.models.blocks.Mlp
    in_features: *dim_latent
    out_features: 1
    hidden_layers: !!python/tuple []
    output_act:
      name: torch.nn.Identity
    dropout: *dropout
    
  init_cond_mean_net:
    name: fim.models.blocks.Mlp
    in_features: *dim_latent
    out_features: 1
    hidden_layers: !!python/tuple [*hidden_dim_mlp, *hidden_dim_mlp, *hidden_dim_mlp, *hidden_dim_mlp]
    hidden_act:
      name: torch.nn.SELU
    output_act:
      name: torch.nn.SELU
    dropout: *dropout
  
  init_cond_var_net:
    name: fim.models.blocks.Mlp
    in_features: *dim_latent
    out_features: 1
    hidden_layers: !!python/tuple [*hidden_dim_mlp, *hidden_dim_mlp, *hidden_dim_mlp, *hidden_dim_mlp]
    hidden_act:
      name: torch.nn.SELU
    output_act:
      name: torch.nn.SELU
    dropout: *dropout
