# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Test

on:
  push:
    branches:
      - "develop"
  pull_request:
    branches:
      - "develop"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true
          python-version: "3.12"

      - name: Install project
        run: uv sync

      - name: Check code formatting with Ruff
        run: uv run ruff format --diff

      - name: Lint code with Ruff
        run: uv run ruff check --output-format=github

      - name: Test with pytest
        run: uv run pytest --cov=fim --cov-report=html --cov-report=term
