# This workflow will install Python dependencies and run tests on Jupyter notebooks.
# It is configured to run ONLY manually from the GitHub Actions tab.

name: Test Tutorial Notebooks

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "latest"
          enable-cache: true
          python-version: "3.12"

      - name: Install project and tutorial dependencies
        run: uv sync --group tutorial

      - name: Build Jupyter Book HTML and Check Links
        working-directory: tutorial
        run: uv run --project .. --group tutorial jupyter-book build --html --check-links --strict

      - name: Test notebooks with pytest and nbmake # some of them take too long for github actions, but can run locally
        env:
            API_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          uv run --group tutorial pytest \
            --nbmake \
            --nbmake-timeout=300 \
            --ignore=tutorial/05_sde/sde_tutorial.ipynb \
            --ignore=tutorial/03_mjp/mjp_usage.ipynb \
            tutorial/
